#!/usr/bin/env bash
# Configure your Nginx server to redirect any hits to the /redirect_me
# endpoint to twitter
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/jossvega103 permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart

