#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*


options=\
"bind :80
        mode http
        use_backend mybackend
backend mybackend
        balance roundrobin
        server 971-web-01 54.242.176.4:80 check
        server 971-web-02 54.162.88.196:80 check
"

sed -i '/errorfile 504/a frontend myconf' /etc/haproxy/haproxy.cfg
sed -i "s/frontend myconf/&$options/g" /etc/haproxy/haproxy.cfg
sudo service haproxy restart