#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*

options="\n\tbind :80\n\tmode http\n\tuse_backend mybackend\nbackend mybackend\n\tbalance roundrobin\n\tserver 971-web-01 54.242.176.4:80 check\n\tserver 971-web-01 54.242.176.4:80 check"

sudo sed -i '/errorfile 504/a frontend myconf' /etc/haproxy/haproxy.cfg
sudo sed -i "s/frontend myconf/&$options/g" /etc/haproxy/haproxy.cfg
sudo service haproxy restart