#!/usr/bin/env bash
# this code will >display the time for 12 hours #and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

((hours=0))
((minutes=1))
#print the hour zero
echo "Hour:$hours"
while ((hours <= 12))
do
	#if minutes equal to 59
	if ((minutes == 60))
	then
		#reset minutes
		((minutes=1))
		#add one to hours
		((hours++))
		#print the hour only if it's smaller or equal to 12
		if ((hours <= 12))
		then
			echo "Hour:$hours"
		fi
	fi
	#only if hours smaller or equal to 12
	if ((hours <= 12))
	then
		echo $minutes
	fi
	((minutes++))
done