#!/usr/bin/env bash
# check if a file exists or not, empty or not etc...

# take the file name, passed by the user as an arg
filename="school"


if [ -e "$filename" ]
#file exists
then 
	echo "school file exists"
	#check if file is not empty
	if [ -s "$filename" ]
	then 
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	#check if file is a regular file not(dir/device_file)
	if [ -f "$filename" ]
	then
		echo "school is a regular file"
	fi
# files donsn't exist
else
	echo "school file does not exist"
fi
