#!/usr/bin/env bash
# change the /etc/hosts file to fullfil the following >
## facebook will be resolved to 8.8.8.8
## 127.0.0.1 will be resolved to 127.0.0.2

# make a copy of the hosts file
cp /etc/hosts ~/hosts.new

# add the new ips to the copied files
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# recopy to the /etc/hosts
cp -f ~/hosts.new /etc/hosts